spring:
  data:
    mongodb:
      uri: "mongodb+srv://unholy:15Bhzxc778%40@cluster0.6gtjz.mongodb.net"
      database: "conflux"
      auto-index-creation: true
  profiles:
    active: dev

server:
  port: 8081
  servlet:
    context-path: ""